#:schema node_modules/wrangler/config-schema.json
name = "server"
main = "src/index.ts"
compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]


[[durable_objects.bindings]]
name = "GroceriesDurableObjects"
class_name = "GroceriesDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["GroceriesDurableObject"]
